sensor_msgs/Image image
sensor_msgs/PointCloud2 cloud
uint8 pattern_width
uint8 pattern_height
float64 pattern_distance
float64 neighbor_distance
string tag_frame
string target_frame
---
geometry_msgs/Transform transform
